.PHONY: all

# If the test doesn't support 32bits or 64bits targets, skip it
ifeq ($(XLEN),32)
ifeq ($(NO_32BITS_SUPPORT),1)
skip:
endif
endif
ifeq ($(XLEN),64)
ifeq ($(NO_64BITS_SUPPORT),1)
skip:
endif
endif

HOST_CC := $(CC)

all: $(target) $(if $(HOST),$(O)/$(TARGET)-host.x,$(O)/$(TARGET).expected)

$(O)/%-host.x: $(patsubst %.o,%.c,$(OBJS))
	$(HOST_CC) $^ -o $@ $(EXTRA_CFLAGS) $(EXTRA_LIBS)

$(O)/%.expected: %.expected
	cp $^ $@

CFLAGS += $(EXTRA_CFLAGS)
include $(RV_ARIANE)/makefile.include
