.PHONY: all

HOST_CC := $(CC)

all: $(target) $(if $(HOST),$(O)/$(TARGET)-host.x,$(O)/$(TARGET).expected)

$(O)/%-host.x: $(wildcard *.c)
	$(HOST_CC) $^ -o $@ $(EXTRA_CFLAGS) $(EXTRA_LIBS)

$(O)/%.expected: %.expected
	cp $^ $@

CFLAGS += $(EXTRA_CFLAGS)
include $(RV_ARIANE)/makefile.include
