TARGET = mvt
OBJS = mvt.o /home/fred/128-test/global/global-tests/examples/polybench/polybench-code/utilities/polybench.o
EXTRA_INCLUDES=-I/home/fred/128-test/global/global-tests/examples/polybench/polybench-code/utilities -I/home/fred/128-test/global/global-tests/../utils/headers/
include $(RVB_BUILD)/makefile.include
