TARGET = gramschmidt
OBJS = gramschmidt.o ../../../utilities/polybench.o
EXTRA_INCLUDES=-I../../../utilities -I../../../../../../../utils/headers/
EXTRA_LIBS=-lm
include $(RVB_BUILD)/makefile.include
